apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: alert-hosts-status-reports
  namespace: ops-system
spec:
  keywords:
    - alerting
  subject: ops.clusters.*.namespaces.ops-system.taskruns.alert-hosts-status.reports.*
  type: xiezuo
  url: https://xz.wps.cn/api/v1/webhook/send?key= 