apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: alert-ray-zombie-processes-reports
  namespace: ops-system
spec:
  keywords:
    matchMode: ALL
    include:
      - alerting
      - alert-ray-zombie-processes
  subject: ops.clusters.*.nodes.*.findings
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
