apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: alert-cluster-cert
  namespace: ops-system
spec:
  keywords:
    matchMode: ALL
    include:
      - alerting
      - alert-cluster-cert
  subject: ops.clusters.*.findings
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
