apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: alert-mount-timeout
  namespace: ops-system
spec:
  additional: "action: clear-mount"
  keywords:
    matchMode: ALL
    include:
      - alerting
      - alert-mount-timeout
  subject: ops.clusters.*.nodes.*.findings
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
