apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: alert-npu
  namespace: ops-system
spec:
  keywords:
    matchMode: ALL
    matchType: REGEX
    include:
      - alerting
      - .*alert-npu-.*
  subject: ops.clusters.*.nodes.*.findings
  type: xiezuo
  url: https://xxx.com/api/v1/webhook/send?key=
