apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: drain-error-gpu
  namespace: ops-system
spec:
  keywords:
    matchMode: ALL
    include:
      - alerting
      - drain-error-gpu
  subject: ops.clusters.*.nodes.*.findings
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
