apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: nodes
  namespace: ops-system
spec:
  keywords:
    - faild
    - xid
    - GPUUnhealthy
    - NodeNotSchedulable
    - NodeSchedulable
  subject: ops.clusters.*.nodes.>
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
