apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: pods-no-free-node
  namespace: ops-system
spec:
  additional: "action: restart-kubelet-bypod"
  keywords:
    include:
      - no free node
  subject: ops.clusters.*.namespaces.*.pods.*.events
  type: webhook
  url: http://x.x.x.x/webhook
