apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: pods-backoff
  namespace: ops-system
spec:
  keywords:
    - BackOff
  subject: ops.clusters.*.namespaces.*.pods.*.event
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=