apiVersion: crd.chenshaowen.com/v1
kind: EventHooks
metadata:
  name: pods
  namespace: ops-system
spec:
  keywords:
    include:
      - Evicted
      - OOMKilled
  subject: ops.clusters.*.namespaces.*.pods.*.events
  type: xiezuo
  url: https://365.kdocs.cn/woa/api/v1/webhook/send?key=
