apiVersion: crd.chenshaowen.com/v1
kind: TaskRun
metadata:
  name: alert-gpu-ecc
  namespace: ops-system
spec:
  desc: alert gpu ecc every hour at 30 minutes
  crontab: "30 * * * *"
  taskRef: alert-gpu-ecc
  variables:
    threshold: "1"