apiVersion: crd.chenshaowen.com/v1
kind: TaskRun
metadata:
  name: alert-juicefs-worker-pod-status
  namespace: ops-system
spec:
  desc: alert juicefs worker pod status every hour at 30 minutes
  crontab: "30 * * * *"
  taskRef: alert-pod-status
  variables:
    labels: "role=juicefs-worker"