apiVersion: crd.chenshaowen.com/v1
kind: TaskRun
metadata:
  name: alert-evicted-pods
  namespace: ops-system
spec:
  desc: alert evicted pods every hour at 30 minutes
  crontab: "30 * * * *"
  taskRef: alert-evicted-pods
  variables:
    threshold: "10"
