apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: clear-mount
  namespace: ops-system
spec:
  desc: clear mount
  host: managed-by=ops
  steps:
    - name: clear-mount
      content: |
        count=0
        max_retries=5

        while [ $count -lt $max_retries ]; do
            count=$((count + 1))
            echo "Attempt #$count"
            timeout 3s df -h 2>&1 > /dev/null
            if [ $? -eq 124 ]; then
                strace_df=$(timeout -k 1s 3s strace df 2>&1)
                last_line=$(echo "$strace_df" | tail -n 1)
                last_mount_path=$(echo "$last_line" | grep -oE '/[^ ",]+' | tail -n 1)
                
                echo "hang: $last_mount_path"
                umount -f "$last_mount_path" && echo "success umount: $last_mount_path" || echo "failed umount: $last_mount_path"
                continue
            fi
            error_paths=$(df -h 2>&1 | grep 'Transport endpoint is not connected' | awk -F': ' '{print $2}')
            for path in $error_paths; do
                umount -f "$path" && echo "Successfully unmounted: $path" || echo "Failed to unmount: $path"
            done
            break
        done
