apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: clear-pod-terminating
  namespace: ops-system
spec:
  host: anymaster
  desc: clear ops
  steps:
    - name: clear ops task pod
      content: |
        kubectl get pods --all-namespaces | grep -E 'Terminating' | awk '{print $1, $2}' | xargs -n2 -P 10 sh -c 'kubectl delete pod $1 -n $0 --force --grace-period=0'
