apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: default
  namespace: ops-system
spec:
  desc: chat with llm
  host: anynode
  steps:
    - name: default
      content: |
        echo "holding"