apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: get-node-status
  namespace: ops-system
spec:
  desc: get node status
  host: anymaster
  variables:
    nodename:
      display: node name
      required: true
  steps:
    - name: get node status
      content: kubectl get nodes ${nodename} -o wide
    - name: get usage
      content: kubectl top nodes ${nodename}

