apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: inspect-pod
  namespace: ops-system
spec:
  desc: get pod details in cluster
  host: anymaster
  variables:
    namespace:
      display: namespace
      required: true
    pod:
      display: pod name
      required: true
  steps:
    - name: get pod details info
      content: kubectl describe pod ${pod} -n ${namespace}
