apiVersion: crd.chenshaowen.com/v1
kind: Task
metadata:
  name: list-pods-bynode
  namespace: ops-system
spec:
  desc: list pods in special node
  host: anymaster
  variables:
    nodename:
      required: true
  steps:
    - name: list pods
      content: |
        kubectl get pods -A --field-selector spec.nodeName=${nodename} -o custom-columns="NAME:.metadata.name,AGE:.metadata.creationTimestamp,STATUS:.status.phase" --sort-by=.metadata.creationTimestamp
