apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: app-npu-exporter
  namespace: ops-system
spec:
  desc: 安装、卸载 npu-exporter 组件
  tasks:
    - name: npu-exporter
      desc: Install or uninstall npu-exporter component
      taskRef: app-npu-exporter

