apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: app-volcano
  namespace: ops-system
spec:
  desc: 安装、卸载 volcano 组件
  tasks:
    - name: volcano
      desc: Install or uninstall volcano component
      taskRef: app-volcano
