apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: clear-pod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: clear abnormal pods
  tasks:
    - name: clear-pod
      desc: clear abnormal pods
      taskRef: clear-pod
