apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: clear-pod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 清理异常的 Pod
  tasks:
    - name: clear-pod
      taskRef: clear-pod
