apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: collect-gpu-log
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Collect - 搜集 GPU 的相关日志
  tasks:
    - name: collect-gpu-log
      desc: Collect GPU related logs
      taskRef: collect-gpu-log
