apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: collect-npu-log
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Collect - 搜集 npu 的相关日志
  tasks:
    - name: 收集 npu 日志
      taskRef: collect-npu-log
