apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: cordon-node
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 禁用集群中的某个节点
  tasks:
    - name: whitelist-pod
      desc: Check whitelist for pod
      taskRef: check-whitelist
    - name: cordon-node
      desc: Cordon node in cluster
      taskRef: cordon-node
