apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: cordon-node
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 禁用集群中的某个节点
  tasks:
    - name: 白名单 Pod
      taskRef: check-whitelist
    - name: 禁用节点
      taskRef: cordon-node
