apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: create-dataload
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 预热数据集
  tasks:
    - name: create-dataset-preload-task
      desc: Create dataset preload task
      taskRef: create-dataload
