apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: create-namespace
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 创建 namespace
  tasks:
    - name: create-namespace
      desc: Create namespace
      taskRef: create-namespace
