apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: create-dataload
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Preload dataset
  tasks:
    - name: create-dataset-preload-task
      desc: Create dataset preload task
      taskRef: create-dataload
