apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: default
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: chat with llm, if you don't know what to do, just choose this
  variables:
    host:
      default: anynode
  tasks:
    - name: default
      taskRef: default
