apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-host
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Delete host object
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: delete-specified-host
      desc: Delete specified host
      taskRef: delete-host
