apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod-bylog
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 重启、删除集群中的某一个 Pod
  tasks:
    - name: get-pod
      desc: Get pod information
      taskRef: get-pod
    - name: delete-pod
      desc: Delete pod by log
      taskRef: delete-pod-bylog
