apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-svc-bymetricsnot200
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 通过 svc 查询 Pod 的非 200 指标判断是否删除 Pod
  tasks:
    - name: 获取 svc
      taskRef: get-svc
    - name: 获取 Metrics 非 200 增量 by svc
      taskRef: get-metrics-svc-not200
    - name: 获取 Metrics 非 200 增量
      taskRef: get-metrics-pod-not200
    - name: 删除异常指标的 Pod
      taskRef: delete-pod-bymetricsnot200
