apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod-force
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 强制删除 Pod
  tasks:
    - name: 白名单 Pod
      taskRef: check-whitelist
    - name: 获取 Pod
      taskRef: get-pod
    - name: 删除 Pod
      taskRef: delete-pod-force
