apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod-force
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 强制删除 Pod
  tasks:
    - name: whitelist-pod
      desc: Check whitelist for pod
      taskRef: check-whitelist
    - name: get-pod
      desc: Get pod information
      taskRef: get-pod
    - name: delete-pod
      desc: Force delete pod
      taskRef: delete-pod-force
