apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-kas-job
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 删除指定的 KAS Job
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: delete-related-pod
      desc: Delete related pods for KAS job
      taskRef: delete-kas-job
