apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod-not200-bymetrics
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 查询 Pod 的非 200 指标判断是否删除 Pod
  tasks:
    - name: get-pod
      desc: Get pod information
      taskRef: get-pod
    - name: get-metrics-not200-increment
      desc: Get metrics not 200 increment
      taskRef: get-metrics-pod-not200
    - name: delete-abnormal-metric-pod
      desc: Delete pod with abnormal metrics
      taskRef: delete-pod-bycounts
