apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: restart or delete a pod in the cluster
  tasks:
    - name: get-pod
      desc: get pod information
      taskRef: get-pod
    - name: delete-pod
      desc: delete pod
      taskRef: delete-pod
