apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: delete-pod-not200-bysvcmetrics
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 通过 svc 查询 Pod 的非 200 指标判断是否删除 Pod
  variables:
    - name: pod
      desc: pod name
      required: false
  tasks:
    - name: 通过 svc 获取 pod 非 200 Metrics
      taskRef: get-metrics-pod-not200-bysvc
    - name: 获取 pod 非 200 增量 metrics
      taskRef: get-metrics-pod-not200
    - name: 删除异常指标的 Pod
      taskRef: delete-pod-bycounts
