apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: drain-node
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  variables:
    cluster:
      value: ""
    host:
      value: ""
    content:
      value: |
        #!/bin/bash

        URL="http://x.x.x.x/api/v1/copilot/execute?action=drain-node&cluster=${cluster}&host=${host}&username=username"

        if ! curl -f --location "$URL" --header 'copilot-token: xxx'; then
            echo "drain node failed"
        else
            echo "drain node success"
        fi
  desc: drain node
  tasks:
    - name: drain-node
      desc: drain node
      taskRef: script
