apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: get-public-ip
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Get egress and public IP
  tasks:
    - name: get-public-ip
      desc: Get egress and public IP
      taskRef: get-public-ip
