apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: get-dataset-status
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 查看数据集的状态
  tasks:
    - name: query-dataset-status
      desc: Query dataset status
      taskRef: get-dataset-status
