apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: get-node-status
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Check if node is ready
  tasks:
    - name: query-node-status
      desc: Query node readiness status
      taskRef: get-node-status
