apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: get-pod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: View pod information and status
  tasks:
    - name: get-pod-status
      desc: View pod information and status
      taskRef: get-pod