apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: inspect-svc-error
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: svc 处于异常状态时，用来查看 svc 的错误日志和错误事件
  tasks:
    - name: get-svc
      desc: Get service information
      taskRef: get-svc
    - name: get-deployment
      desc: Get deployment by service
      taskRef: get-deployment-bysvc
    - name: view-svc-error-logs
      desc: View service error logs
      taskRef: get-pod-error-logs-bysvc
    - name: view-svc-error-events
      desc: View service error events
      taskRef: list-error-events-bysvc
