apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: inspect-pod-restart
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: pod 重启时，用来查看 pod 的状态和事件
  tasks:
    - name: 获取 Pod
      taskRef: get-pod
    - name: 查看 Pod 重启前的错误日志
      taskRef: get-pod-ago-error-logs-byname
    - name: 查看 Pod 重启后的错误日志
      taskRef: get-pod-error-logs-byname
