apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: inspect-pod-restart
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: view pod status and events when pod restarts
  tasks:
    - name: get-pod
      desc: get pod information
      taskRef: get-pod
    - name: view-pod-restart-error-logs
      desc: view pod error logs before restart
      taskRef: get-pod-error-logs-previous-byname
