apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: inspect-pod-error
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: pod 处于异常状态时，用来查看 pod 的错误日志和错误事件
  tasks:
    - name: get-pod
      desc: Get pod information
      taskRef: get-pod
    - name: view-pod-error-logs
      desc: View pod error logs
      taskRef: get-pod-error-logs-byname
    - name: view-pod-error-events
      desc: View pod error events
      taskRef: list-error-events-bypod
