apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: list-hosts
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: list all hosts in the ops-system namespace
  tasks:
    - name: list-hosts
      desc: list all hosts in the ops-system namespace
      taskRef: list-hosts
