apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: list-nodes
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 查看、列出某个集群的所有节点
  tasks:
    - name: list-cluster-nodes
      desc: List all nodes in cluster
      taskRef: list-nodes
    - name: list-cluster-nodes
      desc: List all nodes in cluster
      taskRef: list-nodes
