apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: list-namespace
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 列出、查看所有的命名空间
  tasks:
    - name: list-all-namespaces
      desc: List and view all namespaces
      taskRef: list-namespaces