apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: list-clusters
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: list and view all clusters
  tasks:
    - name: list-all-clusters
      desc: list and view all clusters
      taskRef: list-clusters