apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: list-datasets
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 列出命名空间下的数据集
  tasks:
    - name: list-datasets
      desc: List datasets in namespace
      taskRef: list-datasets
