apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: preload-image
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: preload images in cluster
  tasks:
    - name: preload
      desc: preload images in cluster
      taskRef: preload-image