apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-kubelet
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 重启 kubelet
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: restart-kubelet
      desc: Restart kubelet
      taskRef: restart-kubelet