apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-fabricmanager
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: restart fabricmanager
  tasks:
    - name: whitelist-check
      desc: check whitelist
      taskRef: check-whitelist
    - name: restart-fabricmanager
      desc: restart fabricmanager
      taskRef: restart-fabricmanager