apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-containerd
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 重启 containerd
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: restart-containerd
      desc: Restart containerd
      taskRef: restart-containerd