apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-gpu-manager-bypod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 重启 Pod 所在节点的 gpu-manager 容器
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: get-pod-node
      desc: Get pod node information
      taskRef: get-pod-node
    - name: restart-gpu-manager-container
      desc: Restart gpu-manager container on pod node
      taskRef: restart-gpu-manager
