apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-node
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  variables:
    cluster:
      value: "cluster1"
    host:
      value: "host1"
    whitelist:
      value: "whitelist1"
  desc: restart node or host
  tasks:
    - name: restart-node
      desc: restart node or host
      taskRef: restart-node
