apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-kubelet-bypod
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 重启 Pod 所在节点的 kubelet
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: get-pod-node
      desc: Get pod node information
      taskRef: get-pod-node
    - name: restart-kubelet
      desc: Restart kubelet on pod node
      taskRef: restart-kubelet
