apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: restart-gpu-manager
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: Restart gpu-manager container on node
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: restart-gpu-manager-container
      desc: Restart gpu-manager container on node
      taskRef: restart-gpu-manager
