apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: retag-image
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 转存、retag 容器镜像
  tasks:
    - name: whitelist-check
      desc: Check whitelist
      taskRef: check-whitelist
    - name: retag-image
      desc: Transfer and retag container image
      taskRef: retag-image

