apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: retag-image
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: transfer and retag container images
  tasks:
    - name: whitelist-check
      desc: check whitelist
      taskRef: check-whitelist
    - name: retag-image
      desc: transfer and retag container image
      taskRef: retag-image

