apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: search-clusterip
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: View and search cluster IPs
  tasks:
    - name: search-clusterip
      desc: Search and view cluster IPs
      taskRef: search-clusterip
