apiVersion: crd.chenshaowen.com/v1
kind: Pipeline
metadata:
  name: uncordon-node
  namespace: ops-system
  labels:
    ops/copilot: enabled
spec:
  desc: 恢复集群中的某一个节点
  tasks:
    - name: uncordon-node
      desc: Uncordon node in cluster
      taskRef: uncordon-node
    - name: view-node
      desc: View node status
      taskRef: get-node-status
