name: Release Latest Version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-options: '--depth=0'

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Create or update latest tag
        run: |
          if git rev-parse latest >/dev/null 2>&1; then
            git tag -d latest
            git push origin :refs/tags/latest
          fi
          git tag latest
          git push origin latest

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: latest
          release_name: Latest Release
          body: |
            This is an automated release of the latest version.
          draft: false
          prerelease: false 